---
title: flat_minimal.Rmd empty
output: html_document
editor_options:
  chunk_output_type: console
fusen:
  pkg: '.'
  open_vignette: yes
  check: yes
  document: yes
  overwrite: ask
  flat_file: '"dev/flat_minimal.Rmd"'
  vignette_name: '"Minimal"'
  toto: '"bibi"'
---

```{r development, include = FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->


```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# my_fun

```{r function-my_fun}
#' my_fun Title
#'
#' @return 1
#' @export
#'
#' @examples
my_fun <- function() {
  1
}
```

```{r examples-my_fun}
my_fun()
```

```{r tests-my_fun}
test_that("my_fun works", {

})
```

```{r development-inflate, eval = FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd", vignette_name = "Minimal", toto = "bibi")
```

