---
title: "flat_sepuku.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# sepuku

```{r function-sepuku}
#' Clean a package from fusen-related files and tags
#' This function will remove all the flat files and the fusen-related tags from the package. It will also remove the configuration file if it exists.
#'
#' @param pkg Character. Path of the current package
#' @param force logical. whether to force the cleaning or not, without asking if the user is sure about making this operation (default: FALSE)
#' @return a cleaned package
#' @export
sepuku <- function(
    pkg = ".",
    force = FALSE) {
  if (!dir.exists(file.path(pkg, "dev"))) {
    cli::cli_abort("No dev/ folder have been found. Are you sure that your package has been initiated with fusen ?")
  }

  config_file <- getOption("fusen.config_file", default = "dev/config_fusen.yaml")

  if (!file.exists(config_file)) {
    cli::cli_alert_info("No fusen configuration file found. The flat files to be deleted will be identified as rmd or qmd files starting with 'flat' in the dev/ and dev/flat_history folders.")
  } else {
    cli::cli_alert_info("A fusen configuration file was found. The flat files to be deleted will be identified as files listed in this configuration file as well as rmd or qmd files starting with 'flat' in the dev/ and dev/flat_history folders. The configuration file will also be deleted.")
  }

  flat_files <- list_flat_files(pkg = pkg)

  if (length(flat_files) == 0) {
    cli::cli_alert_info("No flat files were detected.")
  } else {
    cli::cli_alert_info(
      paste0(
        "The following flat files were detected and will therefore be deleted from your package:\n",
        paste0(flat_files, collapse = "\n")
      )
    )
  }

  files_to_be_modified <- find_files_with_fusen_tags(pkg = pkg)
  if (length(files_to_be_modified) == 0) {
    cli::cli_alert_info("No fusen-related tags have been found in any files located in R/, tests/ and vignettes/ folders.")
  } else {
    cli::cli_alert_info(
      paste0(
        "The following files have been identified as containing fusen-related tags and will therefore be modified:\n",
        paste0(files_to_be_modified, collapse = "\n")
      )
    )
  }

  if (length(flat_files) == 0 && length(files_to_be_modified) == 0) {
    return(invisible(NULL))
  }

  do_it <- force

  if (!force) {
    cli::cli_alert_danger("Some files are about to be deleted or modified. This operation is irreversible.")
    sure <- paste(
      "\nAre you sure of what you are doing? (y/n)\n"
    )
    clean <- readline(sure) == "y" || readline(sure) == "yes"
    if (isTRUE(clean) || clean == "yes") {
      do_it <- TRUE
    } else if (isFALSE(clean) || clean == "no") {
      do_it <- FALSE
    } else {
      stop("clean should be TRUE, FALSE, 'yes'or 'no'")
    }
  }

  if (isTRUE(do_it)) {
    if (length(flat_files) > 0) {
      invisible(
        lapply(
          flat_files,
          function(f) {
            file.remove(file.path(pkg, f))
          }
        )
      )
    }

    if (length(files_to_be_modified) > 0) {
      invisible(
        lapply(
          files_to_be_modified,
          function(f) {
            clean_fusen_tags_in_files(pkg = pkg, files_to_clean = f)
          }
        )
      )
    }
    if (file.exists(config_file)) {
      file.remove(config_file)
    }
  }

  cli::cli_alert_info("Cleaning is done !")

  return(invisible(TRUE))
}
```

```{r examples-sepuku, eval=FALSE}
#' \dontrun{
sepuku()
# If you want to force the cleaning, you can use the force argument
sepuku(force = TRUE)

# Example with a dummy package with a flat file
dummypackage <- tempfile("sepuku.example")
dir.create(dummypackage)
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))

usethis::with_project(dummypackage, {
  # Add licence
  usethis::use_mit_license("John Doe")

  dir.create(file.path(dummypackage, "dev"))
  dir.create(file.path(dummypackage, "dev", "flat_history"))

  # We add 2 flat files in the package and inflate them
  dev_file1 <- add_minimal_flat(
    pkg = dummypackage,
    flat_name = "flat1.Rmd",
    open = FALSE
  )

  dev_file2 <- add_minimal_flat(
    pkg = dummypackage,
    flat_name = "flat2.Rmd",
    open = FALSE
  )

  inflate(
    pkg = dummypackage,
    flat_file = dev_file1,
    vignette_name = "Get started",
    check = FALSE,
    open_vignette = FALSE,
    document = TRUE,
    overwrite = "yes"
  )

  inflate(
    pkg = dummypackage,
    flat_file = dev_file2,
    vignette_name = "Get started 2",
    check = FALSE,
    open_vignette = FALSE,
    document = TRUE,
    overwrite = "yes"
  )

  # We deprecate the first flat file, which will be moved to the flat_history folder
  deprecate_flat_file(
    file.path(dummypackage, "dev", "flat_flat1.Rmd")
  )

  # We create 2 flat files with the qmd extension
  file.create(file.path(dummypackage, "dev", "flat_history", "flat_old.qmd"))
  file.create(file.path(dummypackage, "dev", "flat_qmd.qmd"))

  sepuku(force = TRUE)

  # We check that the fusen configuration file has been deleted
  file.exists(
    file.path(dummypackage, "dev", "config_fusen.yaml")
  )

  # We check that all the flat files have been deleted
  length(
    list.files(file.path(dummypackage, "dev"),
      pattern = "flat_.*\\.Rmd"
    )
  )

  length(
    list.files(file.path(dummypackage, "dev"),
      pattern = "flat_.*\\.qmd"
    )
  )


  length(
    list.files(file.path(dummypackage, "dev", "flat_history"),
      pattern = "flat_.*\\.Rmd"
    )
  )


  length(
    list.files(file.path(dummypackage, "dev", "flat_history"),
      pattern = "flat_.*\\.qmd"
    )
  )

  # We check that all the files with fusen tags have been cleaned
  length(fusen:::find_files_with_fusen_tags(pkg = dummypackage))
})

# Clean the temporary directory
unlink(dummypackage, recursive = TRUE)
#' }
```

```{r tests-sepuku}
dummypackage <- tempfile(paste0(sample(letters, 10), collapse = ""))
dir.create(dummypackage)
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))

test_that("sepuku is a function", {
  expect_true(inherits(sepuku, "function"))
})

usethis::with_project(dummypackage, {
  # Add licence
  usethis::use_mit_license("John Doe")

  test_that("sepuku checks that a dev/ folder exists", {
    #  Check for a dev folder
    expect_error(
      sepuku(force = TRUE),
      "No dev/ folder have been found. Are you sure that your package has been initiated with fusen ?"
    )
  })


  test_that("sepuku checks whether a fusen config file exists or not", {
    dir.create(file.path(dummypackage, "dev"))
    expect_message(
      sepuku(force = TRUE),
      "No fusen configuration file found. The flat files to be deleted will be identified as rmd or qmd files starting with 'flat' in the dev/ and dev/flat_history folders."
    )
  })

  dev_file1 <- add_minimal_flat(
    pkg = dummypackage,
    flat_name = "flat1.Rmd",
    open = FALSE
  )

  # To add the config file a first inflate is needed
  suppressMessages(
    inflate(
      pkg = dummypackage, flat_file = dev_file1,
      vignette_name = "Get started", check = FALSE,
      open_vignette = FALSE, document = TRUE,
      overwrite = "yes"
    )
  )

  expect_message(
    sepuku(force = TRUE),
    "A fusen configuration file was found. The flat files to be deleted will be identified as files listed in this configuration file as well as rmd or qmd files starting with 'flat' in the dev/ and dev/flat_history folders. The configuration file will also be deleted."
  )
})


unlink(dummypackage, recursive = TRUE)
```


```{r tests-sepuku}
dummypackage <- tempfile(paste0(sample(letters, 10), collapse = ""))
dir.create(dummypackage)
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))

usethis::with_project(dummypackage, {
  # Add licence
  usethis::use_mit_license("John Doe")

  dir.create(file.path(dummypackage, "dev"))


  test_that("sepuku warns the user if no flat files were detected", {
    expect_message(
      sepuku(force = TRUE),
      "No flat files were detected."
    )
  })



  test_that("sepuku informs the user about the flat files that were detected", {
    dir.create(file.path(dummypackage, "dev", "flat_history"))
    file.create(file.path(dummypackage, "dev", "flat_history", "flat_old.Rmd"))
    file.create(file.path(dummypackage, "dev", "flat_history", "flat_old.qmd"))
    file.create(file.path(dummypackage, "dev", "flat_qmd.qmd"))
    dev_file1 <- add_minimal_flat(
      pkg = dummypackage,
      flat_name = "flat1.Rmd",
      open = FALSE
    )
    inflate(
      pkg = dummypackage,
      flat_file = dev_file1,
      vignette_name = "Get started",
      check = FALSE,
      open_vignette = FALSE,
      document = TRUE,
      overwrite = "yes"
    )

    expect_message(
      sepuku(force = TRUE),
      "The following flat files were detected and will therefore be deleted from your package:\ndev/flat_flat1.Rmd\ndev/flat_qmd.qmd\ndev/flat_history/flat_old.Rmd\ndev/flat_history/flat_old.qmd"
    )
  })
})
unlink(dummypackage, recursive = TRUE)


dummypackage <- tempfile(paste0(sample(letters, 10), collapse = ""))
dir.create(dummypackage)
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))

usethis::with_project(dummypackage, {
  # Add licence
  usethis::use_mit_license("John Doe")

  dir.create(file.path(dummypackage, "dev"))
  usethis::use_r("some_R_file.R", open = FALSE)
  usethis::use_test("some_test.R", open = FALSE)
  dir.create(file.path(dummypackage, "vignettes"))
  file.create(file.path(dummypackage, "vignettes", "somevignette.Rmd"))


  test_that("sepuku warns the user if no files in R, tests or vignettes have to be modified", {
    expect_message(
      sepuku(force = FALSE),
      "No fusen-related tags have been found in any files located in R/, tests/ and vignettes/ folders."
    )
  })



  test_that("sepuku informs the user about the files with fusen tags that were detected", {
    dev_file1 <- add_minimal_flat(
      pkg = dummypackage,
      flat_name = "flat1.Rmd",
      open = FALSE
    )
    inflate(
      pkg = dummypackage,
      flat_file = dev_file1,
      vignette_name = "Get started",
      check = FALSE,
      open_vignette = FALSE,
      document = TRUE,
      overwrite = "yes"
    )
    dev_file2 <- add_minimal_flat(
      pkg = dummypackage,
      flat_name = "flat2.Rmd",
      open = FALSE
    )
    inflate(
      pkg = dummypackage,
      flat_file = dev_file2,
      vignette_name = "Get started 2",
      check = FALSE,
      open_vignette = FALSE,
      document = TRUE,
      overwrite = "yes"
    )

    expect_message(
      sepuku(force = TRUE),
      "The following files have been identified as containing fusen-related tags and will therefore be modified:\nR/flat1_rmd.R\nR/flat2_rmd.R\ntests/testthat/test-flat1_rmd.R\ntests/testthat/test-flat2_rmd.R\nvignettes/get-started-2.Rmd\nvignettes/get-started.Rmd"
    )
  })
})
unlink(dummypackage, recursive = TRUE)

dummypackage <- tempfile(paste0(sample(letters, 10), collapse = ""))
dir.create(dummypackage)
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))


usethis::with_project(dummypackage, {
  # Add licence
  usethis::use_mit_license("John Doe")
  test_that("sepuku informs the user than modifying / deleting files can not be undone if force = FALSE", {
    dev_file1 <- add_minimal_flat(
      pkg = dummypackage,
      flat_name = "flat1.Rmd",
      open = FALSE
    )
    inflate(
      pkg = dummypackage,
      flat_file = dev_file1,
      vignette_name = "Get started",
      check = FALSE,
      open_vignette = FALSE,
      document = TRUE,
      overwrite = "yes"
    )


    if (interactive()) {
      test_that("sepuku tells the users that files will be modified or deleted and that it is irreversible", {
        expect_message(
          sepuku(force = FALSE),
          "Some files are about to be deleted or modified. This operation is irreversible."
        )
      })
    }
  })
})
unlink(dummypackage, recursive = TRUE)

dummypackage <- tempfile(paste0(sample(letters, 10), collapse = ""))
dir.create(dummypackage)
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))

usethis::with_project(dummypackage, {
  # Add licence
  usethis::use_mit_license("John Doe")

  dir.create(file.path(dummypackage, "dev"))
  dir.create(file.path(dummypackage, "dev", "flat_history"))

  dev_file1 <- add_minimal_flat(
    pkg = dummypackage,
    flat_name = "flat1.Rmd",
    open = FALSE
  )

  dev_file2 <- add_minimal_flat(
    pkg = dummypackage,
    flat_name = "flat2.Rmd",
    open = FALSE
  )

  inflate(
    pkg = dummypackage,
    flat_file = dev_file1,
    vignette_name = "Get started",
    check = FALSE,
    open_vignette = FALSE,
    document = TRUE,
    overwrite = "yes"
  )

  inflate(
    pkg = dummypackage,
    flat_file = dev_file2,
    vignette_name = "Get started 2",
    check = FALSE,
    open_vignette = FALSE,
    document = TRUE,
    overwrite = "yes"
  )

  deprecate_flat_file(
    file.path(dummypackage, "dev", "flat_flat1.Rmd")
  )

  file.create(file.path(dummypackage, "dev", "flat_history", "flat_old.qmd"))
  file.create(file.path(dummypackage, "dev", "flat_qmd.qmd"))

  sepuku(force = TRUE)

  expect_false(
    file.exists(
      file.path(dummypackage, "dev", "config_fusen.yaml")
    )
  )
  expect_equal(
    length(
      list.files(file.path(dummypackage, "dev"),
        pattern = "flat_.*\\.Rmd"
      )
    ),
    0
  )

  expect_equal(
    length(
      list.files(file.path(dummypackage, "dev"),
        pattern = "flat_.*\\.qmd"
      )
    ),
    0
  )

  expect_equal(
    length(
      list.files(file.path(dummypackage, "dev", "flat_history"),
        pattern = "flat_.*\\.Rmd"
      )
    ),
    0
  )

  expect_equal(
    length(
      list.files(file.path(dummypackage, "dev", "flat_history"),
        pattern = "flat_.*\\.qmd"
      )
    ),
    0
  )

  expect_equal(
    length(find_files_with_fusen_tags(pkg = dummypackage)),
    0
  )
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_sepuku.Rmd",
  vignette_name = NA,
  check = FALSE,
  overwrite = TRUE,
  open_vignette = FALSE
)
```

