---
title: "dev_history.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(tools)
```

# My function

```{r function-1}
#' Add flat Rmd file that drives package development
#'
#' @param template Name of the template to use. See details.
#' @param pkg Path where to save file
#' @param overwrite Whether to overwrite existing flat Rmd template file with same name
#' @param open Logical. Whether to open file after creation
#' @param dev_dir Name of directory for development Rmarkdown files. Default to "dev".
#' @param flat_name Name of the file to write in dev.
#' Use the name of the main function of your template to get chunks pre-filled with this function name. 
#'
#' @importFrom tools file_path_sans_ext
#' @details
#' Choose `template` among the different templates available:
#'
#' - "full": The full template with a reproducible package that can directly be inflated.
#' It comes along with the "dev_history" template. Default.
#' - "minimal": Minimal template to start a new package when you already know {fusen}, along with the "dev_history" template.
#' - "additional": Template for an additional vignette or set of additional functions.
#' - "teaching": Template with a reproducible package, simpler than "full", but everything to
#'  teach the minimal structure of a package.
#' - "dev_history": Template with functions commonly used during package development.
#' This does not contain chunks to write your own functions.
#'
#' Abbreviated names can also be used for the different templates:
#' "add" for additional, "min" for minimal, "teach" for teaching, "dev" for "dev_history".
#' 
#' `add_additional()`, `add_minimal()`, `add_full()` are wrapper around `add_flat_template("additional")`, ...
#' However, `add_dev_history()` is a deprecated function from a previous version.
#'
#' @rdname add_flat_template
#' @return
#' Create flat Rmd file(s) template(s) and return its (their) path
#' @export
#'
#' @examples
add_flat_template <- function(
    template = c("full", "minimal", "additional", "teaching", "dev_history"),
    pkg = ".", 
    dev_dir = "dev",
    flat_name = template,
    overwrite = FALSE,
    open = TRUE) {
  
  project_name <- get_pkg_name(pkg = pkg)
  
  if (project_name != asciify_name(project_name, to_pkg = TRUE)) {
    stop("Please rename your project/directory with: `", asciify_name(project_name, to_pkg = TRUE),
         "` as a package name should only contain letters, numbers and dots.")
  }
  
  template <- match.arg(template)
  if (!template %in% c("full", "teaching", "dev_history")
      & !flat_name %in% c("minimal", "additional")) {
    fun_name <- gsub("-", "_", asciify_name(flat_name))
  } else {
    fun_name <- NA
  }
  flat_name <- paste0("flat_", 
                      asciify_name(gsub("[.]Rmd$", "", flat_name[1])), ".Rmd")
  
  pkg <- normalizePath(pkg)
  full_dev_dir <- file.path(pkg, dev_dir)
  if (!dir.exists(full_dev_dir)) {dir.create(full_dev_dir)}
  dev_file_path <- file.path(full_dev_dir, flat_name) #"dev_history.Rmd")
  
  # Which template ----
  if (template == "dev_history") {
    dev_file_path <- character(0)
  } else {
    template_file <- system.file(paste0("flat-template-", template, ".Rmd"), package = "fusen")
    
    if (file.exists(dev_file_path) & overwrite == FALSE) {
      n <- length(list.files(full_dev_dir, pattern = "^flat_.*[.]Rmd"))
      dev_file_path <- file.path(full_dev_dir, paste0(file_path_sans_ext(flat_name), "_", n + 1, ".Rmd"))
      message(
        flat_name, " already exists. New flat file is renamed '",
        basename(dev_file_path), "'. Use overwrite = TRUE, if you want to ",
        "overwrite the existing file or rename it."
      )
    }
    dev_name <- basename(dev_file_path)
    
    # Change lines asking for pkg name
    lines_template <- readLines(template_file)
    
    lines_template[grepl("<my_package_name>", lines_template)] <-
      gsub("<my_package_name>", project_name,
           lines_template[grepl("<my_package_name>", lines_template)])
    
    # Change flat_template file name
    # _inflate
    lines_template[grepl("dev/flat_template.Rmd", lines_template)] <-
      gsub("dev/flat_template.Rmd", file.path(dev_dir, dev_name),
           lines_template[grepl("dev/flat_template.Rmd", lines_template)])
    # _title
    lines_template[grepl("flat_template.Rmd", lines_template)] <-
      gsub("flat_template.Rmd", dev_name,
           lines_template[grepl("flat_template.Rmd", lines_template)])
    
    # Change my_fun to fun_name
    if (!is.na(fun_name)) {
      lines_template[grepl("my_fun", lines_template)] <-
        gsub("my_fun", fun_name,
             lines_template[grepl("my_fun", lines_template)])
    }
    
    cat(enc2utf8(lines_template), file = dev_file_path, sep = "\n")
  }
  
  # Add the-dev-history when needed ----
  if (template %in% c("full", "minimal", "dev_history")) {
    dev_file <- file.path(full_dev_dir, "0-dev_history.Rmd")
    if (file.exists(dev_file) & !isTRUE(overwrite)) {
      message("'0-dev_history.Rmd' already exists. It was not overwritten. ",
              "Set `add_flat_template(overwrite = TRUE)` if you want to do so.")
    } else {
      copy <- file.copy(
        system.file("the-dev-history.Rmd", package = "fusen"),
        dev_file,
        overwrite = overwrite
      )
      if (!copy) {
        stop("'0-dev_history.Rmd' could not be created in '", full_dev_dir, "'")
      }
      dev_file_path <- c(dev_file_path, dev_file)
    }
    
  }
  
  # Add data for the full template exemple
  if (template %in% c("full")) {
    inst_dir <- file.path(pkg, "inst")
    # Create "inst/" directory
    if (!dir.exists(inst_dir)) {
      dir.create(inst_dir)
    }
    # Example dataset
    file.copy(system.file("nyc_squirrels_sample.csv", package = "fusen"), inst_dir)
  }
  
  # .Rbuildignore ----
  # usethis::use_build_ignore(dev_dir) # Cannot be used outside project
  if (length(list.files(pkg, pattern = "[.]Rproj")) == 0) {
    lines <- c(paste0("^", dev_dir, "$"), "^\\.here$")
  } else {
    lines <- c(paste0("^", dev_dir, "$"))
  }
  
  buildfile <- normalizePath(file.path(pkg, ".Rbuildignore"), mustWork = FALSE)
  if (!file.exists(buildfile)) {
    existing_lines <- ""
  } else {
    existing_lines <- readLines(buildfile, warn = FALSE, encoding = "UTF-8")
  }
  new <- setdiff(lines, existing_lines)
  if (length(new) != 0) {
    all <- c(existing_lines, new)
    cat(enc2utf8(all), file = buildfile, sep = "\n")
  }
  
  # Add a gitignore file in dev_dir ----
  # Files to ignore
  lines <- c("*.html", "*.R")
  
  gitfile <- normalizePath(file.path(full_dev_dir, ".gitignore"), mustWork = FALSE)
  if (!file.exists(gitfile)) {
    existing_lines <- ""
  } else {
    existing_lines <- readLines(gitfile, warn = FALSE, encoding = "UTF-8")
  }
  new <- setdiff(lines, existing_lines)
  if (length(new) != 0) {
    all <- c(existing_lines, new)
    cat(enc2utf8(all), file = gitfile, sep = "\n")
  }
  
  if (length(list.files(pkg, pattern = "[.]Rproj")) == 0) {
    here::set_here(pkg)
  }
  if (isTRUE(open) & interactive()) {usethis::edit_file(dev_file_path)}
  
  dev_file_path
}
```

```{r examples-1}
# Create a new project
dummypackage <- tempfile("dummypackage")
dir.create(dummypackage)

# Add
add_flat_template(template = "teaching", pkg = dummypackage)
# Delete dummy package
unlink(dummypackage, recursive = TRUE)

# For classical use in your package
#' \dontrun{
# first time ever using 'fusen'
add_flat_template("full") 

# first time in your new package
add_flat_template("minimal")

# add new flat file for new functions
add_flat_template("add")

# add new flat template for teaching (a reduced full template)
add_flat_template("teaching")
#'}
```

```{r tests-1}
# Create a new project
dummypackage <- tempfile(pattern = "add.flat.template")
dir.create(dummypackage)
pkg_name <- basename(dummypackage)

# add_flat_template ----
test_that("add_flat_template adds flat_template.Rmd and co.", {
  dev_file_path <- expect_error(add_flat_template(pkg = dummypackage, open = FALSE), 
                                regexp = NA)
  flat_file <- dev_file_path[grepl("flat_", dev_file_path)]
  
  expect_true(all(file.exists(dev_file_path)))
  expect_true(file.exists(file.path(dummypackage, "dev", "0-dev_history.Rmd")))
  expect_true(file.exists(file.path(dummypackage, ".here")))
  expect_true(file.exists(file.path(dummypackage, "inst", "nyc_squirrels_sample.csv")))
  
  rbuildignore_file <- file.path(dummypackage, ".Rbuildignore")
  expect_true(file.exists(rbuildignore_file))
  rbuildignore_lines <- readLines(rbuildignore_file)
  expect_true(any(grepl("^dev$", rbuildignore_lines, fixed = TRUE)))
  expect_true(any(grepl("[.]here", rbuildignore_lines)))
  
  dev_lines <- readLines(flat_file)
  expect_equal(length(grep(pkg_name, dev_lines)), 3)
  
  # Second time message and new file
  expect_message(add_flat_template(pkg = dummypackage))
  expect_true(file.exists(file.path(dummypackage, "dev", "flat_full_2.Rmd")))
  # _New file has path changed in title and inflate
  lines_2 <- readLines(file.path(dummypackage, "dev", "flat_full_2.Rmd"))
  expect_length(grep(x = lines_2, pattern = "flat_full_2[.]Rmd"), 2)
})
unlink(dummypackage, recursive = TRUE)

# Test with .Rproj and no .here, it works ----
# Create a new project
dummypackage2 <- tempfile(pattern = "rproj.nohere")
dir.create(dummypackage2)
cat("", file = file.path(dummypackage2, 'dummy.Rproj'))

# Add
dev_file_path <- add_flat_template(pkg = dummypackage2, open = FALSE)
flat_file <- dev_file_path[grepl("flat", dev_file_path)]

test_that("add_flat_template works with .Rproj and no .here", {
  expect_true(all(file.exists(dev_file_path)))
  expect_false(file.exists(file.path(dummypackage2, ".here")))
  
  rbuildignore_file <- file.path(dummypackage2, ".Rbuildignore")
  expect_true(file.exists(rbuildignore_file))
  rbuildignore_lines <- readLines(rbuildignore_file)
  expect_true(any(grepl("dev", rbuildignore_lines, fixed = TRUE)))
  expect_false(any(grepl("[.]here", rbuildignore_lines)))
})
unlink(dummypackage2, recursive = TRUE)

# Test "dev_history" template ----
dummypackage <- tempfile(pattern = "dev.history.template")
dir.create(dummypackage)
# Add
test_that("add dev_history template works", {
  withr::with_dir(dummypackage, {
    dev_file_path <- expect_error(add_flat_template(pkg = dummypackage, template = "dev_history", open = FALSE), regexp = NA)
    
    expect_true(file.exists(dev_file_path))
    
    usethis::with_project(dummypackage, {
      
      # Extract and test the description chunk
      dev_lines <- readLines(dev_file_path)
      # Change path of project
      dev_lines <- gsub(
        "here::here()",
        # To correct for Windows path
        paste0('"', gsub("\\\\", "\\\\\\\\", dummypackage), '"'), dev_lines,
        # paste0('"', newdir, '"'), dev_lines, 
        fixed = TRUE)
      dev_parse <- parsermd::parse_rmd(dev_lines)
      desc_code <- tempfile("desc")
      parsermd::rmd_select(dev_parse, "description")[[1]] %>% 
        parsermd::rmd_node_code() %>% 
        cat(., sep = "\n", file = desc_code)
      # Execute code
      expect_error(source(desc_code), regexp = NA)
    })
    expect_true(file.exists(file.path(dummypackage, "DESCRIPTION")))
    expect_true(file.exists(file.path(dummypackage, "LICENSE")))
    expect_true(file.exists(file.path(dummypackage, "LICENSE.md")))
    
  })
})

unlink(dummypackage)


# Test "dev_history" template ----
dummypackage <- tempfile(pattern = "dev.history.template.uu")
dir.create(dummypackage)
# Add
test_that("add dev_history template works with windows \\users path", {
  withr::with_dir(dummypackage, {
    dev_file_path <- expect_error(
      add_flat_template(pkg = dummypackage, template = "dev_history",
                        open = FALSE),
      regexp = NA)
    
    expect_true(file.exists(dev_file_path))
    # Test specific \\users path
    newdir_uu <- tempfile("aa\\U/gzv")
    dir.create(newdir_uu, recursive = TRUE)
    
    usethis::with_project(dummypackage, {
      # Extract and test the description chunk
      dev_lines <- readLines(dev_file_path)
      # Change path of project
      dev_lines <- gsub(
        "here::here()",
        # To correct for Windows path
        paste0('"', gsub("\\\\", "\\\\\\\\", newdir_uu), '"'), dev_lines,
        # paste0('"', newdir_uu, '"'), dev_lines,
        fixed = TRUE)
      dev_parse <- parsermd::parse_rmd(dev_lines)
      desc_code <- tempfile("desc", fileext = ".R")
      parsermd::rmd_select(dev_parse, "description")[[1]] %>% 
        parsermd::rmd_node_code() %>% 
        cat(., sep = "\n", file = desc_code)
      # Execute code
      expect_error(source(desc_code), regexp = NA)
    })
    # DESCRIPTION in newdir_uu as created by fill_description()
    expect_true(file.exists(file.path(newdir_uu, "DESCRIPTION")))
    # LICENSE.md in dummypackage as created by use_mit_license()
    # No LICENSE because of separation of DESCRIPTION
    # expect_true(file.exists(file.path(dummypackage, "LICENSE")))
    expect_true(file.exists(file.path(dummypackage, "LICENSE.md")))
    
  })
})

unlink(dummypackage)

# Add failed with malformed package name ----
# Create a new project
dummypackage3 <- tempfile(pattern = "malformed_pkg")
dir.create(dummypackage3)
cat("", file = file.path(dummypackage3, 'dummy.Rproj'))

# Add
test_that("add_flat_template fails", {
  expect_error(add_flat_template(pkg = dummypackage3, open = FALSE), "package name")
})
unlink(dummypackage3, recursive = TRUE)

# More complicated example for tests
# This will render the Rmd template that is supposed to build a package
# But we need to be inside a project,
# in the correct working directory,
# with the correct here()

# Test all templates to knit ----
all_templates <- c("full", "minimal", "additional", "teaching") # "dev_history"

for (template in all_templates) {
  dummypackage4 <- tempfile(pattern = "all.templates.knit")
  dir.create(dummypackage4)
  # Add
  dev_file_path <- add_flat_template(pkg = dummypackage4, template = template, open = FALSE)
  flat_file <- dev_file_path[grepl("flat", dev_file_path)]
  
  # Change lines asking for pkg name
  lines_template <- readLines(system.file("tests-templates/dev-template-tests.Rmd", package = "fusen"))
  lines_template[grepl("<my_package_name>", lines_template)] <-
    gsub("<my_package_name>", basename(dummypackage4),
         lines_template[grepl("<my_package_name>", lines_template)])
  cat(enc2utf8(lines_template), file = flat_file, sep = "\n")
  
  withr::with_dir(dummypackage4, {
    usethis::proj_set(dummypackage4)
    here:::do_refresh_here(dummypackage4)
    
    if (rmarkdown::pandoc_available("1.12.3")) {
      rmarkdown::render(
        input = file.path(dummypackage4, "dev", paste0("flat_", template, ".Rmd")),
        output_file = file.path(dummypackage4, "dev", paste0("flat_", template, ".html")),
        envir = new.env(), quiet = TRUE)
    }
  })
  
  test_that(paste0("template", template, "runs as markdown"), {
    expect_true(file.exists(file.path(dummypackage4, "dev", paste0("flat_", template, ".Rmd"))))
    if (template %in% c("full", "minimal")) {
      expect_true(file.exists(file.path(dirname(flat_file), "0-dev_history.Rmd")))
    }
    
    if (rmarkdown::pandoc_available("1.12.3")) {
      expect_true(file.exists(file.path(dummypackage4, "DESCRIPTION")))
      expect_true(file.exists(file.path(dummypackage4, "LICENSE")))
      if (template %in% c("full", "teaching")) {
        expect_true(file.exists(file.path(dummypackage4, "inst", "nyc_squirrels_sample.csv")))
      }
      expect_true(file.exists(file.path(dummypackage4, "dev", paste0("flat_", template, ".html"))))
    }
  })
  unlink(dummypackage4, recursive = TRUE)
} # end of loop on template knit


# Test other names modifies template ----
dummypackage <- tempfile(pattern = "other.names")
dir.create(dummypackage)
# Add
test_that("Other flat_name works", {
  # Template additional used with "add"
  dev_file_path <- expect_error(
    add_flat_template(
      template = "add", 
      pkg = dummypackage, flat_name = "hello", open = FALSE),
    regexp = NA)
  expect_true(file.exists(file.path(dummypackage, "dev/flat_hello.Rmd")))
  hello_flat <- readLines(dev_file_path)
  # 7 times hello for function name
  # 2 times hello in flat_hello.Rmd
  expect_equal(length(grep("hello", hello_flat)), 7 + 2)
  expect_equal(length(grep("flat_hello[.]Rmd", hello_flat)), 2)
  
  # Template minimal used with "min", same name, flat changes name
  expect_message(
    add_flat_template(
      template = "min", 
      pkg = dummypackage, flat_name = "hello", open = FALSE),
    regexp = "flat_hello.Rmd already exists.")
  flat_file <- file.path(dummypackage, "dev/flat_hello_2.Rmd")
  expect_true(file.exists(flat_file))
  hello_flat <- readLines(flat_file)
  # 7 times hello for function name
  # 2 times hello in flat_hello_2.Rmd
  expect_equal(length(grep("hello", hello_flat)), 7 + 2)
  expect_equal(length(grep("flat_hello_2[.]Rmd", hello_flat)), 2)
  
  # Try inflate to see if files get hello name
  usethis::with_project(dummypackage, {
    fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))
    expect_error(
      inflate(pkg = dummypackage, flat_file = flat_file,
              vignette_name = "hello", check = FALSE,
              open_vignette = FALSE), 
      regexp = NA)
  })
  
  expect_true(file.exists(file.path(dummypackage, "R", "hello.R")))
  expect_true(file.exists(file.path(dummypackage, "tests", "testthat", "test-hello.R")))
  expect_true(file.exists(file.path(dummypackage, "vignettes", "hello.Rmd")))
  test_hello <- readLines(file.path(dummypackage, "tests", "testthat", "test-hello.R"))
  expect_true(any(grepl("hello works", test_hello)))
  vignette_hello <- readLines(file.path(dummypackage, "vignettes", "hello.Rmd"))
  expect_true(any(grepl("title: \"hello\"", vignette_hello)))
  expect_true(any(grepl("  %\\VignetteIndexEntry{hello}", vignette_hello, fixed = TRUE)))
  expect_true(any(grepl("hello()", vignette_hello)))
})
# Delete dummy package
unlink(dummypackage, recursive = TRUE)

# Test other dev_dir works ----
dummypackage <- tempfile(pattern = "devdir")
dir.create(dummypackage)
# Add
test_that("Other dev_dir works", {
  # Template additional used with "add"
  dev_file_path <- expect_error(
    add_flat_template(
      template = "add", 
      pkg = dummypackage, flat_name = "hello", 
      dev_dir = "devdir",
      open = FALSE),
    regexp = NA)
  expect_true(file.exists(file.path(dummypackage, "devdir/flat_hello.Rmd")))
  hello_flat <- readLines(dev_file_path)
  
  # 7 times hello for function name
  # 2 times hello in flat_hello.Rmd
  # 1 time devdir/flat_hello.Rmd
  # O time dev/flat_hello.Rmd
  expect_equal(length(grep("hello", hello_flat)), 7 + 2)
  expect_equal(length(grep("flat_hello[.]Rmd", hello_flat)), 2)
  expect_equal(length(grep("devdir/flat_hello[.]Rmd", hello_flat)), 1)
  expect_equal(length(grep("dev/flat_hello[.]Rmd", hello_flat)), 0)
})
# Delete dummy package
unlink(dummypackage, recursive = TRUE)
```

## add_additional

```{r function-add_additional}
#' @rdname add_flat_template
#' @export
add_additional <- function(
    pkg = ".", 
    dev_dir = "dev",
    flat_name = "additional",
    overwrite = FALSE,
    open = TRUE) {
  add_flat_template(
    template = "additional",
    pkg = pkg, 
    dev_dir = dev_dir,
    flat_name = flat_name,
    overwrite = overwrite,
    open = open) 
}

#' @rdname add_flat_template
#' @export
add_minimal <- function(
    pkg = ".", 
    dev_dir = "dev",
    flat_name = "minimal",
    overwrite = FALSE,
    open = TRUE) {
  add_flat_template(
    template = "minimal",
    pkg = pkg, 
    dev_dir = dev_dir,
    flat_name = flat_name,
    overwrite = overwrite,
    open = open) 
}

#' @rdname add_flat_template
#' @export
add_full <- function(
    pkg = ".", 
    dev_dir = "dev",
    flat_name = "full",
    overwrite = FALSE,
    open = TRUE) {
  add_flat_template(
    template = "full",
    pkg = pkg, 
    dev_dir = dev_dir,
    flat_name = flat_name,
    overwrite = overwrite,
    open = open) 
}
```

```{r example-add_additional}
```

```{r tests-add_additional}
dummypackage <- tempfile(pattern = "add.wrappers")
dir.create(dummypackage)
pkg_name <- basename(dummypackage)

# add_full ----
test_that("add_full adds flat_full.Rmd", {
  dev_file_path <- expect_error(add_full(pkg = dummypackage, open = FALSE), 
                                regexp = NA)
  flat_file <- dev_file_path[grepl("flat_", dev_file_path)]
  
  expect_true(all(file.exists(dev_file_path)))
  expect_true(file.exists(file.path(dummypackage, "dev", "0-dev_history.Rmd")))
  expect_true(file.exists(file.path(dummypackage, ".here")))
  expect_true(file.exists(file.path(dummypackage, "inst", "nyc_squirrels_sample.csv")))
  
  rbuildignore_file <- file.path(dummypackage, ".Rbuildignore")
  expect_true(file.exists(rbuildignore_file))
  rbuildignore_lines <- readLines(rbuildignore_file)
  expect_true(any(grepl("^dev$", rbuildignore_lines, fixed = TRUE)))
  expect_true(any(grepl("[.]here", rbuildignore_lines)))
  
  dev_lines <- readLines(flat_file)
  expect_equal(length(grep(pkg_name, dev_lines)), 3)
})
unlink(dummypackage, recursive = TRUE)

dummypackage <- tempfile(pattern = "add.wrappers")
dir.create(dummypackage)
pkg_name <- basename(dummypackage)
# add_minimal
test_that("add_minimal adds flat_minimal.Rmd", {
  dev_file_path <- expect_error(add_minimal(pkg = dummypackage, open = FALSE), 
                                regexp = NA)
  flat_file <- dev_file_path[grepl("flat_", dev_file_path)]
  
  expect_true(all(file.exists(dev_file_path)))
  expect_true(file.exists(file.path(dummypackage, "dev", "0-dev_history.Rmd")))
  expect_true(file.exists(file.path(dummypackage, ".here")))
  expect_false(file.exists(file.path(dummypackage, "inst", "nyc_squirrels_sample.csv")))
  
  rbuildignore_file <- file.path(dummypackage, ".Rbuildignore")
  expect_true(file.exists(rbuildignore_file))
  rbuildignore_lines <- readLines(rbuildignore_file)
  expect_true(any(grepl("^dev$", rbuildignore_lines, fixed = TRUE)))
  expect_true(any(grepl("[.]here", rbuildignore_lines)))
  
  dev_lines <- readLines(flat_file)
  expect_equal(length(grep("minimal", dev_lines)), 2)
})
unlink(dummypackage, recursive = TRUE)

dummypackage <- tempfile(pattern = "add.wrappers")
dir.create(dummypackage)
pkg_name <- basename(dummypackage)
# add_additional
test_that("add_additional adds flat_additional.Rmd", {
  dev_file_path <- expect_error(add_additional(pkg = dummypackage, open = FALSE), 
                                regexp = NA)
  flat_file <- dev_file_path[grepl("flat_", dev_file_path)]
  
  expect_true(all(file.exists(dev_file_path)))
  expect_false(file.exists(file.path(dummypackage, "dev", "0-dev_history.Rmd")))
  expect_true(file.exists(file.path(dummypackage, ".here")))
  expect_false(file.exists(file.path(dummypackage, "inst", "nyc_squirrels_sample.csv")))
  
  rbuildignore_file <- file.path(dummypackage, ".Rbuildignore")
  expect_true(file.exists(rbuildignore_file))
  rbuildignore_lines <- readLines(rbuildignore_file)
  expect_true(any(grepl("^dev$", rbuildignore_lines, fixed = TRUE)))
  expect_true(any(grepl("[.]here", rbuildignore_lines)))
  
  dev_lines <- readLines(flat_file)
  expect_equal(length(grep("additional", dev_lines)), 2)
})
unlink(dummypackage, recursive = TRUE)


dummypackage <- tempfile("checkpk.gname2")
dir.create(dummypackage)
# rstudioapi::filesPaneNavigate(dummypackage)
# {fusen} steps

fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package", Package = "COUCOU2"))
dev_file <- suppressMessages(add_flat_template(pkg = dummypackage, overwrite = TRUE, open = FALSE))
flat_file <- dev_file[grepl("flat_", dev_file)]

test_that("get_pkg_name works", {
  flat_file_lines <- readLines(flat_file)
  #the package name must be used and not the project name
  expect_true(any(grepl("COUCOU2", flat_file_lines, fixed = TRUE)))
  expect_false(any(grepl("gname2", flat_file_lines)))
})

unlink(dummypackage, recursive = TRUE)


```


```{r development-inflate, eval=FALSE}
# Got to dev_history.R
rstudioapi::navigateToFile("dev/dev_history.R", line = 95)
# # Run but keep eval=FALSE to avoid infinite loop
# # Execute in the console directly
# fusen::inflate(flat_file = "dev/flat_create_flat.Rmd", check = FALSE,
#                vignette_name = NA)
# # unlink("vignettes/get-started.Rmd")
# attachment::att_amend_desc(
#   pkg_ignore = c("testthat", "dummypackage", "rstudioapi"),
#   extra.suggests = c("testthat", "pkgload", "rstudioapi")
# )
```

