# WARNING - Generated by {fusen} from dev/flat_map_the_package.Rmd: do not edit by hand

test_that("map_the_package works", {
  expect_true(inherits(map_the_package, "function"))
})

# Test full ----
dummypackage <- tempfile("drawmap")
dir.create(dummypackage)

# {fusen} steps
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))
dev_file <- suppressMessages(add_flat_template(pkg = dummypackage, overwrite = TRUE, open = FALSE))
flat_file <- dev_file[grepl("flat_", dev_file)]

usethis::with_project(dummypackage, {
  suppressMessages(
    inflate(
      pkg = dummypackage, flat_file = flat_file,
      vignette_name = "Get started", check = FALSE,
      open_vignette = FALSE
    )
  )

  test_that("map_the_package works", {
    # Need to force edition to allow expect_snapshot
    # As we are in another directory using with_dir()
    local_edition(3)
    # Fix output conditions for this test for snapshots
    local_reproducible_output(
      width = 100,
      crayon = FALSE,
      unicode = FALSE,
      rstudio = FALSE,
      hyperlinks = FALSE,
      lang = "en",
      .env = parent.frame()
    )

    map <- map_the_package()

    expect_snapshot(map)

    expect_snapshot(draw_the_map(map))
  })
})
