# WARNING - Generated by {fusen} from dev/dev_history_parse.Rmd: do not edit by hand

file <- system.file("tests-templates/dev-template-parsing.Rmd",
  package = "fusen"
)
# debugonce(get_rmd_parts)
tbl_rmd <- get_rmd_parts(file)

# get_rmd_parts works as expected ----
test_that("get_rmd_parts gets yaml header data", {
  expect_equal(sum(tbl_rmd[["type"]] == "yaml"), 1)
  w_yaml <- which(tbl_rmd[["type"]] == "yaml")
  expect_equal(
    tbl_rmd[["params"]][[w_yaml]]$title,
    "dev_history.Rmd for working package"
  )
  expect_equal(tbl_rmd[["params"]][[w_yaml]]$author, "statnmap")
  expect_equal(tbl_rmd[["params"]][[w_yaml]]$date, "2023-10-12")
})

# Find all headings
headings <- c(
  "Description of your package",
  "Read data",
  "Calculate the median of a vector",
  "Calculate the mean of a vector",
  "Use sub-functions in the same chunk",
  "Inflate your package"
)

test_that("get_rmd_parts gets titles in markdown part only", {
  expect_equal(sum(tbl_rmd[["type"]] == "heading"), 6)
  expect_equal(tbl_rmd[["heading"]][!is.na(tbl_rmd[["heading"]])], headings)
})

test_that("get_rmd_parts gets text parts without titles", {
  expect_equal(sum(tbl_rmd[["type"]] == "inline"), 16)
  expect_equal(
    sum(tbl_rmd[["type"]] == "inline"),
    length(tbl_rmd[["text"]][!is.na(tbl_rmd[["text"]])]) -
      sum(tbl_rmd[["type"]] == "heading")
  )
  expect_length(tbl_rmd[tbl_rmd[["type"]] == "inline", ][["text"]][[1]], 0)
  expect_equal(
    tbl_rmd[tbl_rmd[["type"]] == "inline", ][["text"]][[3]],
    c("", "This will fill the description of your package.", "-->")
  )
  # Verify there is no title in the lists
  expect_false(any(headings %in%
    unlist(tbl_rmd[tbl_rmd[["type"]] == "inline", ][["text"]])))
})

test_that("get_rmd_parts gets R-only chunks with label and options", {
  expect_equal(sum(tbl_rmd[["type"]] == "block"), 12)
  # labels
  expect_equal(
    tbl_rmd[["label"]][tbl_rmd[["type"]] == "block"],
    c(
      "development", "description", "development-2",
      "function", "examples", "tests",
      "function-1", "examples-1", "tests-1",
      "development-1", "unnamed-chunk-1", "unnamed-chunk-2"
    )
  )
  # options
  expect_equal(
    tbl_rmd[["params"]][tbl_rmd[["type"]] == "block"][[1]],
    list(label = "development", include = FALSE)
  )
  expect_equal(
    tbl_rmd[["params"]][tbl_rmd[["type"]] == "block"][[4]],
    list(label = "function")
  )
  # qmd-like options format
  expect_equal(
    tbl_rmd[["params"]][tbl_rmd[["type"]] == "block"][[7]],
    list(label = "function-1", filename = "the_median_file")
  )
})

test_that("get_rmd_parts - chunk code extracted contains R code only", {
  expect_equal(
    as.character(tbl_rmd[["code"]][tbl_rmd[["type"]] == "block"][[5]]),
    c("my_median(1:12)")
  )
  # No remaining chunk params in the code extracted
  expect_equal(
    as.character(tbl_rmd[["code"]][tbl_rmd[["type"]] == "block"][[7]])[1],
    c("#' My Other median")
  )
})

test_that(
  "get_rmd_parts gets does not increment unnamed-chunks id when run a 2nd time",
  {
    tbl_rmd <- get_rmd_parts(file)
    tbl_rmd <- get_rmd_parts(file) # 2nd time
    expect_equal(sum(tbl_rmd[["type"]] == "block"), 12)
    expect_equal(
      tbl_rmd[["label"]][tbl_rmd[["type"]] == "block"],
      c(
        "development", "description", "development-2",
        "function", "examples", "tests",
        "function-1", "examples-1", "tests-1",
        "development-1", "unnamed-chunk-1", "unnamed-chunk-2"
      )
    )
  }
)
