# WARNING - Generated by {fusen} from dev/flat_map_the_package.Rmd: do not edit by hand

test_that("get_all_created_funs works", {
  expect_true(inherits(get_all_created_funs, "function"))

  file_path <- tempfile(fileext = ".R")
  cat(
    "my_fun <- function() {1}",
    "my_fun2 <- function() {2}",
    sep = "\n",
    file = file_path
  )
  expect_equal(
    get_all_created_funs(file_path),
    c("my_fun", "my_fun2")
  )
})
