# WARNING - Generated by {fusen} from dev/flat_inflate_a_single_rmd.Rmd: do not edit by hand

test_that("list_all_inflate_parameters works", {
  expect_true(inherits(list_all_inflate_parameters, "function")) 
  
  inflate_parameters_already_in_flat_file <- get_inflate_parameters(
    rmd_flat_file = system.file("files_to_parse", "flat_file_to_parse_with_extra_param.Rmd", package = "fusen"))
  
  expect_equal(list_all_inflate_parameters(inflate_parameters_already_in_flat_file),
               list(pkg = ".", open_vignette = TRUE, check = TRUE, document = TRUE, 
                    overwrite = "ask", flat_file = "\"dev/flat_minimal.Rmd\"", 
                    vignette_name = "\"Minimal\"", extra_param = "\"bibi\"")
  )
  
  
  
})
