# WARNING - Generated by {fusen} from dev/flat_inflate_a_single_rmd.Rmd: do not edit by hand

test_that("get_inflate_parameters works", {

  # function raised an error if the file does not exist
  expect_error(
    get_inflate_parameters(rmd_flat_file = system.file("files_to_parse", "flat_file_missing.Rmd", package = "fusen"))
  )

  # returns NULL if the inflate call does not have any parameter
  expect_equal(
    get_inflate_parameters(rmd_flat_file = system.file("files_to_parse", "flat_file_to_parse_with_no_param.Rmd", package = "fusen")),
    structure(list(parameter = "flat_file", value = "dev/flat_file_to_parse_with_no_param.Rmd"), class = c("tbl_df",
                                                                                                           "tbl", "data.frame"), row.names = c(NA, -1L))
  )

  expect_equal(
    get_inflate_parameters(rmd_flat_file = system.file("files_to_parse", "flat_file_to_parse_with_extra_param.Rmd", package = "fusen")),
    structure(list(parameter = c("flat_file", "vignette_name", "extra_param"
    ), value = c("\"dev/flat_minimal.Rmd\"", "\"Minimal\"", "\"bibi\""
    )), row.names = c(NA, -3L), class = c("tbl_df", "tbl", "data.frame"
    ))
  )

})
