# WARNING - Generated by {fusen} from dev/dev_history_parse.Rmd: do not edit by hand

file <- system.file("tests-templates/dev-template-parsing.Rmd",
  package = "fusen"
)
tbl_rmd <- get_rmd_parts(file)
tbl_rmd_content <- get_content_parsedtbl(tbl_rmd)

test_that("get_content_parsedtbl can create the Rmd content for each type", {
  # yaml
  expect_equal(
    tbl_rmd_content$content[[1]],
    paste(
      c(
        "---",
        "title: dev_history.Rmd for working package",
        "output: html_document",
        "author: statnmap",
        "date: '2023-10-12'",
        "editor_options:",
        "  chunk_output_type: console",
        "---",
        ""
      ),
      collapse = "\n"
    )
  )
  # chunk
  expect_equal(
    tbl_rmd_content$content[[3]],
    "```{r development}\n#| include: no\n\nlibrary(testthat)\n```\n"
  )
  # title
  expect_equal(
    tbl_rmd_content$content[[5]],
    "# Description of your package"
  )
  # text
  expect_equal(
    tbl_rmd_content$content[[6]],
    "\nThis will fill the description of your package.\n-->"
  )
  # no params and no label
  expect_equal(
    tbl_rmd_content$content[[32]],
    "```{r}\n# duplicate empty name\n```\n" 
  )
  # test the content of chunk description
  expect_true(
    all(
      grepl("^```\\{r description\\}", tbl_rmd_content$content[[7]]),
      !grepl("#\\| label: description", tbl_rmd_content$content[[7]]),
      grepl("# --> for parse tests", tbl_rmd_content$content[[7]]),
      grepl("\\nfusen::fill_description", tbl_rmd_content$content[[7]]),
      grepl("\\nusethis::use_mit_license", tbl_rmd_content$content[[7]]),
      grepl("```\\n$", tbl_rmd_content$content[[7]])
    )
  )
})

test_that("combine_parsed perfectly recreates the content of R chunks", {
  out_content <- combine_parsed(tbl_rmd_content)
  temp_purl_original <-
    suppressMessages(
      knitr::purl(
        file,
        output = tempfile(fileext = ".Rmd"),
        documentation = 0,
        quiet = TRUE
      )
    )
  temp_purl_output <-
    suppressMessages(
      knitr::purl(
        text = out_content,
        output = tempfile(fileext = ".Rmd"),
        documentation = 0,
        quiet = TRUE
      )
    )
  expect_equal(readLines(temp_purl_output), readLines(temp_purl_original))
})
