# WARNING - Generated by {fusen} from /dev/flat_clean_fusen_files.Rmd: do not edit by hand

# Test df_to_config with custom config file path ----
config_file_path <- tempfile(fileext = ".yaml")

test_that("df_to_config fails when appropriate", {
  withr::with_options(list(fusen.config_file = config_file_path), {
    all_files <- tibble::tribble(
      ~type, ~files,
      "R", "zaza.R",
      "R", "zozo.R",
      "test", "test-zaza.R"
    )
    
    expect_error(df_to_config(all_files, flat_file_path = "keep"),
                 "df_files should contains two columns named: 'type' and 'path'")
    
    all_files <- tibble::tribble(
      ~type, ~path,
      "R", "zaza.R",
      "R", "zozo.R",
      "test", "test-zaza.R"
    )
    
    expect_error(
      df_to_config(all_files),
      "Some files in df_files do not exist:  R: zaza.R, R: zozo.R, test: test-zaza.R")
  })
})

# Create files, even empty
dir_tmp <- tempfile()
dir.create(dir_tmp)
file.create(file.path(dir_tmp, c("zaza.R", "zozo.R", "test-zaza.R")))
    
test_that("df_to_config works", {
  withr::with_options(list(fusen.config_file = config_file_path), {

    # Use full path
    all_files <- tibble::tribble(
      ~type, ~path,
      "R", file.path(dir_tmp, "zaza.R"),
      "R", file.path(dir_tmp, "zozo.R"),
      "test", file.path(dir_tmp, "test-zaza.R")
    )
    
   expect_message(config_file_out <- df_to_config(all_files))
  })
  
  expect_equal(config_file_out, config_file_path)
  all_keep <- yaml::read_yaml(config_file_out)
  expect_equal(names(all_keep), "keep")
  expect_equal(names(all_keep$keep), c("path", "R", "tests", "vignettes"))
  expect_equal(all_keep$keep$path, c("keep"))
  expect_equal(basename(all_keep$keep$R), c("zaza.R", "zozo.R"))
  expect_equal(basename(all_keep$keep$tests), c("test-zaza.R"))
  expect_equal(all_keep$keep$vignettes, list())
})

# Second pass
all_files <- tibble::tribble(
  ~type, ~path,
  "r", file.path(dir_tmp, "tata.R"),
  "R", file.path(dir_tmp, "toto.R"),
  "tests", file.path(dir_tmp, "test-tata.R"),
  "vignettes", file.path(dir_tmp, "tata_vignette.Rmd")
)

file.create(file.path(dir_tmp, c("tata.R", "toto.R", "test-tata.R", "tata_vignette.Rmd")))

withr::with_options(list(fusen.config_file = config_file_path), {
  # debugonce(df_to_config)
  expect_message(config_file <- df_to_config(all_files)) # "keep" is default
})

# rstudioapi::navigateToFile(config_file)

test_that("not_registered_files works", {
  expect_true(inherits(not_registered_files, "function")) 
})


# Test full ----
# Change options(fusen.config_file = "dev/config_fusen.yaml")
dummypackage <- tempfile("clean")
dir.create(dummypackage)

# {fusen} steps
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))
dev_file <- suppressMessages(add_flat_template(pkg = dummypackage, overwrite = TRUE, open = FALSE))
flat_file <- dev_file[grepl("flat_", dev_file)]

# Detect all files created ----
usethis::with_project(dummypackage, {
  browser()

  # Create empty config file

  # Inflate once
  suppressMessages(
    inflate(
      pkg = dummypackage, flat_file = flat_file,
      vignette_name = "Get started", check = FALSE,
      open_vignette = FALSE
    )
  )

  debugonce(inflate)


})



