# WARNING - Generated by {fusen} from dev/flat_inflate_all_utils.Rmd: do not edit by hand

dummypackage <- tempfile("diag")
dir.create(dummypackage)
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))
dev_file <- suppressMessages(add_minimal(pkg = dummypackage, overwrite = TRUE, open = FALSE))

# let's create 2 flat files
flat_file <- dev_file[grepl("flat_", dev_file)]
flat_file2 <- gsub(x = flat_file, pattern = "flat_minimal.Rmd", replacement = "flat_minimal_2.Rmd")
file.copy(from = flat_file, to = flat_file2, overwrite = TRUE)

test_that("pre_inflate_all_diagnosis works", {
  expect_true(inherits(pre_inflate_all_diagnosis, "function"))

  usethis::with_project(dummypackage, {
    # We inflate both flat files
    suppressMessages(
      inflate(
        pkg = dummypackage, flat_file = flat_file,
        vignette_name = "Get started", check = FALSE,
        open_vignette = FALSE
      )
    )

    suppressMessages(
      inflate(
        pkg = dummypackage, flat_file = flat_file2,
        vignette_name = "Get started2", check = FALSE,
        open_vignette = FALSE
      )
    )

    config_yml_ref <- yaml::read_yaml(file.path(dummypackage, "dev/config_fusen.yaml"))

    # all files can be inflated with inflate_all()
    config_yml <- config_yml_ref
    diag <- pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)

    expect_equal(
      diag,
      structure(
        list(
          flat = c("flat_minimal.Rmd", "flat_minimal_2.Rmd"),
          status = structure(
            c(
              "The flat file flat_minimal.Rmd is going to be inflated",
              "The flat file flat_minimal_2.Rmd is going to be inflated"
            ),
            class = c(
              "glue",
              "character"
            )
          ),
          type = c("message", "message")
        ),
        row.names = c(NA, -2L),
        class = c("tbl_df", "tbl", "data.frame")
      )
    )

    #  "not inflated because "inactive or deprecated" (message) : a file is present in config_yml but its state is not 'active'
    config_yml <- config_yml_ref
    config_yml[[1]][["state"]] <- "deprecated"
    diag <- pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)

    expect_equal(
      diag,
      structure(
        list(
          flat = c("flat_minimal.Rmd", "flat_minimal_2.Rmd"),
          status = structure(
            c(
              "The flat file flat_minimal.Rmd is not going to be inflated because it is \"inactive or deprecated\"",
              "The flat file flat_minimal_2.Rmd is going to be inflated"
            ),
            class = c(
              "glue",
              "character"
            )
          ),
          type = c("message", "message")
        ),
        row.names = c(NA, -2L),
        class = c("tbl_df", "tbl", "data.frame")
      )
    )


    #  "not inflated because not in config file please inflate() from the flat once" (warning) : a file is missing from config_yml
    config_yml <- config_yml_ref
    config_yml[[1]] <- NULL
    diag <- pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)

    expect_equal(
      diag,
      structure(
        list(
          flat = c("flat_minimal.Rmd", "flat_minimal_2.Rmd"),
          status = structure(
            c(
              "The flat file flat_minimal.Rmd is not going to be inflated because it is absent from the config file. Please inflate() from the flat once",
              "The flat file flat_minimal_2.Rmd is going to be inflated"
            ),
            class = c(
              "glue",
              "character"
            )
          ),
          type = c("warning", "message")
        ),
        row.names = c(NA, -2L),
        class = c("tbl_df", "tbl", "data.frame")
      )
    )


    #  "not inflated because in config, but without parameters, please inflate() again from the flat with this new 'fusen' version" (stop) : a file is is config_yml but has not inflate parameters
    config_yml <- config_yml_ref
    config_yml[[1]][["inflate"]] <- NULL
    diag <- pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)

    expect_equal(
      diag,
      structure(
        list(
          flat = c("flat_minimal.Rmd", "flat_minimal_2.Rmd"),
          status = structure(
            c(
              "The flat file flat_minimal.Rmd is not going to be inflated because although present in the config file, it has no inflate() parameters. Please inflate() again from the flat with this 'fusen' version",
              "The flat file flat_minimal_2.Rmd is going to be inflated"
            ),
            class = c(
              "glue",
              "character"
            )
          ),
          type = c("stop", "message")
        ),
        row.names = c(NA, -2L),
        class = c("tbl_df", "tbl", "data.frame")
      )
    )

    # a file is in config.yml but missing from dev/
    config_yml <- config_yml_ref
    config_yml[["missing_file.Rmd"]] <- config_yml[[1]]
    diag <- pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)

    expect_equal(
      diag,
      structure(
        list(
          flat = c(
            "flat_minimal.Rmd", "flat_minimal_2.Rmd",
            "missing_file.Rmd"
          ),
          status = structure(
            c(
              "The flat file flat_minimal.Rmd is going to be inflated",
              "The flat file flat_minimal_2.Rmd is going to be inflated",
              "The file missing_file.Rmd is not going to be inflated because it was not found, have you changed the name or did you move in another place ? Maybe you want to set the state as 'deprecated' in the config file"
            ),
            class = c("glue", "character")
          ),
          type = c(
            "message", "message",
            "stop"
          )
        ),
        row.names = c(NA, -3L),
        class = c(
          "tbl_df", "tbl",
          "data.frame"
        )
      )
    )

    # error if we dont have any flat file in dev/
    config_yml <- config_yml_ref
    unlink(flat_file)
    unlink(flat_file2)
    expect_error(pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage))
  })
})

unlink(dummypackage, recursive = TRUE)

test_that("read_inflate_params works", {
  config_fusen_not_existing <-
    system.file("inflate_all/fake.yaml", package = "fusen")
  expect_error(read_inflate_params(config_yml = config_fusen_not_existing))

  config_fusen_existing <-
    yaml::read_yaml(system.file("inflate_all/config_fusen_with_inflate_parameters.yaml",
      package = "fusen"
    ))

  inflate_params <-
    read_inflate_params(config_yml = config_fusen_existing)

  expect_equal(
    length(inflate_params),
    3
  )

  expect_equal(
    names(inflate_params),
    c(
      "flat_full.Rmd",
      "flat_new_one.Rmd",
      "flat_no_inflate_params.Rmd"
    )
  )

  expect_equal(
    inflate_params[["flat_full.Rmd"]],
    list(
      pkg = "fusentest",
      flat_file = "dev/flat_full.Rmd",
      vignette_name = "Get started",
      open_vignette = FALSE,
      check = FALSE,
      document = TRUE,
      overwrite = "ask"
    )
  )

  expect_equal(
    inflate_params[["flat_new_one.Rmd"]],
    list(
      pkg = "fusentest",
      flat_file = "dev/flat_new_one.Rmd",
      vignette_name = "new_one",
      open_vignette = FALSE,
      check = FALSE,
      document = TRUE,
      overwrite = "ask"
    )
  )
  expect_null(inflate_params[["flat_no_inflate_params.Rmd"]])

  # test whether flat files with state = "deprecated" are removed
  config_fusen_with_deprecated <-
    yaml::read_yaml(system.file(
      "inflate_all/config_fusen_with_inflate_parameters_and_some_deprecated_files.yaml",
      package = "fusen"
    ))

  inflate_params <-
    read_inflate_params(config_yml = config_fusen_with_deprecated)

  expect_equal(
    length(inflate_params),
    2
  )

  expect_equal(
    names(inflate_params),
    c("flat_new_one.Rmd", "flat_no_inflate_params.Rmd")
  )
})
