# WARNING - Generated by {fusen} from dev/flat_sepuku-utils.Rmd: do not edit by hand

test_that("list_flat_files_in_config_file is a function", {
  expect_true(inherits(list_flat_files_in_config_file, "function"))
})

dummypackage <- tempfile("listflatfiles.first")
dir.create(dummypackage)
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))
flat_file1 <- add_minimal_package(
  pkg = dummypackage,
  overwrite = TRUE,
  open = FALSE
)
flat_file1 <- flat_file1[grepl("flat_", flat_file1)]


usethis::with_project(dummypackage, {
  # Add licence
  usethis::use_mit_license("John Doe")

  test_that("list_flat_files works when no fusen config file is present", {
    identified_flat_files <- list_flat_files_in_config_file()
    expect_true(!is.null(identified_flat_files))
    expect_equal(identified_flat_files, "")
  })
})

usethis::with_project(dummypackage, {
  test_that("list_flat_files works for a fusen config file", {
    flat_file2 <- add_minimal_flat(
      pkg = dummypackage,
      flat_name = "XXX_flat2.Rmd",
      open = FALSE
    )

    inflate(
      pkg = dummypackage,
      flat_file = flat_file1,
      vignette_name = "Get started",
      check = FALSE,
      open_vignette = FALSE,
      document = TRUE,
      overwrite = "yes"
    )

    inflate(
      pkg = dummypackage,
      flat_file = flat_file2,
      vignette_name = "Get started 2",
      check = FALSE,
      open_vignette = FALSE,
      document = TRUE,
      overwrite = "yes"
    )

    identified_flat_files <- list_flat_files_in_config_file()

    expect_equal(
      length(identified_flat_files), 2
    )

    expect_true(
      all(
        identified_flat_files %in% c("dev/flat_minimal.Rmd", "dev/flat_xxx_flat2.Rmd")
      )
    )
  })
})
unlink(dummypackage, recursive = TRUE)

test_that("list_flat_files_in_dev_folder is a function", {
  expect_true(inherits(list_flat_files_in_dev_folder, "function"))
})

dummypackage <- tempfile("listflatfilesindev.first")
dir.create(dummypackage)
fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))
flat_file1 <- add_minimal_package(
  pkg = dummypackage,
  overwrite = TRUE,
  open = FALSE
)
flat_file1 <- flat_file1[grepl("flat_", flat_file1)]


usethis::with_project(dummypackage, {
  # Add licence
  usethis::use_mit_license("John Doe")

  test_that("list_flat_files_in_dev_folder works for rmd and qmd files in dev folder starting with flat", {
    flat_file_with_bad_name <- "xxx_flat2.Rmd"
    file.create(file.path(dummypackage, "dev", flat_file_with_bad_name))

    identified_flat_files <- list_flat_files_in_dev_folder()

    expect_equal(identified_flat_files, "dev/flat_minimal.Rmd")

    qmd_file <- "flat_minimal.qmd"

    file.create(file.path(dummypackage, "dev", qmd_file))

    identified_flat_files <- list_flat_files_in_dev_folder()

    expect_equal(
      length(identified_flat_files), 2
    )

    expect_true(
      all(
        identified_flat_files %in% c("dev/flat_minimal.Rmd", "dev/flat_minimal.qmd")
      )
    )
  })

  test_that("list_flat_files_in_dev_folder works for rmd and qmd files in flat_history folder starting with flat", {
    inflate(
      pkg = dummypackage,
      flat_file = flat_file1,
      vignette_name = NA,
      check = FALSE,
      open_vignette = FALSE,
      document = TRUE,
      overwrite = "yes"
    )

    deprecate_flat_file(
      flat_file = flat_file1
    )

    identified_flat_files <- list_flat_files_in_dev_folder(folder = "dev/flat_history")

    expect_equal(identified_flat_files, "dev/flat_history/flat_minimal.Rmd")

    qmd_file <- "flat_minimal.qmd"

    file.create(file.path(dummypackage, "dev/flat_history", qmd_file))

    identified_flat_files <- list_flat_files_in_dev_folder(folder = "dev/flat_history")

    expect_equal(
      length(identified_flat_files), 2
    )

    expect_true(
      all(
        identified_flat_files %in% c("dev/flat_history/flat_minimal.Rmd", "dev/flat_history/flat_minimal.qmd")
      )
    )
  })
})
unlink(dummypackage, recursive = TRUE)

# test_that("list_flat_files is a function", {
#   expect_true(inherits(list_flat_files, "function"))
# })

# dummypackage <- tempfile("listflatfiles.first")
# dir.create(dummypackage)
# fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))

# usethis::with_project(dummypackage, {
#   # Add licence
#   usethis::use_mit_license("John Doe")

#   test_that("list_flat_files works for a fusen config file", {
#     dev_file1 <- add_minimal_flat(pkg = dummypackage, flat_name = "flat1.Rmd", open = FALSE)
#     dev_file2 <- add_minimal_flat(pkg = dummypackage, flat_name = "XXX_flat2.Rmd", open = FALSE)

#     inflate(
#       pkg = dummypackage,
#       flat_file = dev_file1,
#       vignette_name = "Get started",
#       check = FALSE,
#       open_vignette = FALSE,
#       document = TRUE,
#       overwrite = "yes"
#     )

#     inflate(
#       pkg = dummypackage,
#       flat_file = dev_file2,
#       vignette_name = "Get started 2",
#       check = FALSE,
#       open_vignette = FALSE,
#       document = TRUE,
#       overwrite = "yes"
#     )

#     config_yml_ref <-
#       yaml::read_yaml(getOption("fusen.config_file", default = "dev/config_fusen.yaml"))
#   })

# Pas de config file et rien dans dev

#  Pas de config file et un fichier dans dev

#  Pas de config file et un fichier dans dev avec un nom qui ne commence pas par flat

# Inflate les 2 : on a un config file

#  Gérer les qmd

# Deprecated un flat file
# })
