---
title: "vignette-template"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette-template}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<!-- BEGIN DESCRIPTION - Do not remove this tag -->
```yaml
Title: Build A Package From Rmarkdown file
Authors@R: c(
  person("Sebastien", "Rochette", email = "sebastien@thinkr.fr", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1565-9313")),
  person(given = "ThinkR", role = "cph")
 )
Description: Use Rmd First method to build your package. Start your package with documentation. Everything can be set from a Rmd file in your project.
```
<!-- END DESCRIPTION - Do not remove this tag -->

<!-- START Documentation - Do not remove this tag -->

## Packages
```{r setup}
library(fusen)
```

## Load dataset for reproducible examples

<!-- SAY what you will do - Do not remove this tag -->

We read the dataset.

<!-- DO what you said - Do not remove this tag -->

```{r}
# -- Preparation code

```


<!-- SAY what you will do - Do not remove this tag -->

# My first function

<!-- DO what you said - Do not remove this tag -->

```{r}
# -- Your function with the roxygen documentation - Do not remove this tag --

# -- Unit test on your function - Do not remove this tag --

# -- Examples use of your function - Do not remove this tag --

```


<!-- END Documentation - Do not remove this tag -->
