# WARNING - Generated by {fusen} from /dev/flat_clean_fusen_files.Rmd: do not edit by hand

#' Title
#'
#' Description
#'
#' @return
#'
#' @export
#' @examples
#' clean_fusen_files()
clean_fusen_files <- function(){

}

#' Add a tibble of files and types to the 'fusen' config file
#' @param df_files A dataframe with 'type' and 'path' columns
#' @param flat_file_path
#'
#' @importFrom stats setNames
#'
#' @return Config file path.
#' Side effect: create a yaml config file.
#'
#' @details
#' - Only types: "R", "test", "vignette" are accepted.
#' - All `path` should exist.
#' - Change path to config file with `options(fusen.config_file = "dev/config_fusen.yaml")`
#'
#' @noRd
#' @examples
#' # Add your own list of files to "keep",
#' # if they are not in a flat file.
#' # Otherwise, they may be deleted with your next `inflate()`
#' my_files_to_protect <- tibble::tribble(
#'   ~type, ~path,
#'   "R", "R/zaza.R",
#'   "R", "R/zozo.R",
#'   "test", "tests/testthat/test-zaza.R",
#'   "vignette", "vignettes/my-zaza-vignette.Rmd"
#' )
#'
#' # \dontrun{
#' df_to_config(my_files_to_protect)
#' # }
#'
df_to_config <- function(df_files, flat_file_path = "keep") {

  # Verify df_files
  if (!is.data.frame(df_files)) {
    stop("df_files should be a dataframe with 'type' and 'path' columns.")
  }
  if (!all(c("type", "path") %in% names(df_files))) {
    stop("df_files should contains two columns named: 'type' and 'path'")
  }
  if (!all(grepl("^R$|^r$|^test$|^tests$|^vignette$|^vignettes$", df_files[["type"]]))) {
    stop("Only types 'R', 'test' or 'vignette' are allowed")
  }
  all_exists <- file.exists(df_files[["path"]])
  if (!all(all_exists)) {
    stop(paste("Some files in df_files do not exist: ",
               paste(
                 paste0(df_files[["type"]][!all_exists], ": ",
                       df_files[["path"]][!all_exists]),
                 collapse = ", ")))
  }

  if (is.null(getOption("fusen.config_file"))) {
    config_file <- "dev/config_fusen.yaml"
  } else {
    config_file <- getOption("fusen.config_file")
  }

  if (file.exists(config_file)) {
    complete_yaml <- yaml::read_yaml(config_file)
    all_keep_before <- complete_yaml[[basename(flat_file_path)]]
    if (!is.null(complete_yaml)) {
      cli::cli_alert_info("This files group already existed, it has been overwritten.")
      complete_yaml[[basename(flat_file_path)]] <- NULL
    }
  } else {
    complete_yaml <- list()
    all_keep_before <- NULL
  }

  this_group_list <- list(
    flat = list(
      path = flat_file_path,
      R = c(df_files$path[grepl("^R$|^r$", df_files$type)]),
      tests = c(df_files$path[grepl("^test$|^tests$", df_files$type)]),
      vignettes = c(df_files$path[grepl("^vignette$|^vignettes$", df_files$type)])
    )
  ) %>% setNames(basename(flat_file_path))

  # All these will be deleted



  files_list_to_vector <- function(list_of_files) {
    lapply(seq_along(list_of_files), function(x) {
      if (length(list_of_files[[x]]) != 0) {
        paste(names(list_of_files[x]), list_of_files[[x]], sep = ": ")
      }
    }) %>% unlist()
  }

  # Those removed
  those_removed <- setdiff(
    all_keep_before,
    this_group_list[[1]]
  )
  those_removed_vec <- files_list_to_vector(those_removed)
  those_added <- setdiff(
    this_group_list[[1]],
    all_keep_before
  )
  those_added_vec <- files_list_to_vector(those_added)



  # Combine with complete_yaml
  complete_yaml <- c(complete_yaml, this_group_list)
  complete_yaml <- complete_yaml[sort(names(complete_yaml))]
  yaml::write_yaml(complete_yaml, file = config_file)
  # rstudioapi::navigateToFile(config_file)

  if (!is.null(those_removed_vec) || length(those_removed_vec) != 0) {
    silent <- lapply(paste(those_removed_vec, "was removed from the config file"), cli::cli_alert_warning)
  }
  if (!is.null(those_added_vec) || length(those_added_vec) != 0) {
    silent <- lapply(paste(those_added_vec, "was added to the config file"), cli::cli_alert_success)
  }

  return(config_file)
}


#' Title
#'
#' Description
#'
#' @return
#'
#' @export
#' @examples
#' not_registered_files()
not_registered_files <- function(){

  # return a `dput()` to allow to add to `df_to_config()`
  # dput()
}
