# WARNING - Generated by {fusen} from dev/flat_inflate_a_single_rmd.Rmd: do not edit by hand

#' Returns the parameters used in an `inflate()` call in some flat Rmd file 
#' 
#' @param rmd_flat_file flat file to parse
#' @return a tibble with 2 columns `parameter` and `value`
#' returns NULL if no parameter are provided in the `inflate()` call
#' @export
#' 
#' @importFrom parsermd parse_rmd rmd_select has_type as_document
#' @importFrom stringr str_split str_trim
#' @importFrom tibble as_tibble tibble
#' @importFrom purrr map_dfr
#' @importFrom dplyr mutate across 
#' @importFrom tidyselect everything
#'
#' @examples
#' get_inflate_parameters(rmd_flat_file = system.file("files_to_parse", "flat_file_to_parse_with_extra_param.Rmd", package = "fusen"))
#' 
#' get_inflate_parameters(rmd_flat_file = system.file("files_to_parse", "flat_file_to_parse_with_no_param.Rmd", package = "fusen"))
#' 
get_inflate_parameters <- function(rmd_flat_file) {
  
  if(!file.exists(rmd_flat_file)) stop("The flat file does not exist")
  
  rmd_tbl <- parse_rmd(rmd_flat_file) %>% 
    as_tibble()
  
  # keep only code chunks
  chunks_only <- rmd_tbl %>% 
    rmd_select(has_type("rmd_chunk"))
  
  chunks_content <- chunks_only[["ast"]] %>% 
    as_document()
  chunks_with_inflate <- chunks_content[sapply(chunks_content, function(chunk) grepl(pattern = "inflate\\(", x = chunk))]
  # it will be needed to deal with multiple inflate call in one rmd ...
  
  parameters_defined_in_chunks <-  gsub(pattern = "fusen::", replacement = "", x = chunks_with_inflate) %>% 
    gsub(pattern = "inflate\\(", replacement = "", x= .) %>% 
    gsub(pattern = "\\)", replacement = "", x= .) %>% 
    str_split(string = ., pattern = ",", simplify = TRUE) %>%
    as.data.frame()
  
  if(parameters_defined_in_chunks$V1 == "") {
    message("The inflate call does not have any parameters")
    return(tibble(
      "parameter" = "flat_file",
      "value" = paste0("dev/", basename(rmd_flat_file))
    )
    )
  }
  
  parameters_defined_in_chunks <- map_dfr(parameters_defined_in_chunks, ~data.frame(str_split(string = .x, pattern = "=", simplify = TRUE))) %>% 
    as_tibble() %>% 
    mutate(across(everything(), ~str_trim(.x)))
  names(parameters_defined_in_chunks) <- c("parameter", "value")
  # it will be needed to deal with the case when no parameters are defined
  
  parameters_defined_in_chunks
  
}
