# WARNING - Generated by {fusen} from dev/dev_history_parse.Rmd: do not edit by hand

#' Group lines of a Rmd or Qmd file by types in a tibble
#'
#' @param file A Rmd or Qmd file path
#' @return A tibble with 6 columns:
#' - `type`: type of the part (yaml, heading, inline, block)
#' - `label`: label of the part (if any)
#' - `params`: parameters of the part (if any)
#' - `text`: text of the part (if any)
#' - `code`: code of the part (if any)
#' - `heading`: heading of the part (if any)
#'
#' @export
#' @examples
#' file <- system.file("tests-templates/dev-template-parsing.Rmd",
#'   package = "fusen"
#' )
#' get_rmd_parts(file)
get_rmd_parts <- function(file) {
  rmd_lines <- readLines(file)
  # Get yaml header
  if (!grepl("^---$", rmd_lines[1])) {
    stop("Flat file parsed needs to have a yaml header starting from line 1 with: ---")
  }
  yaml_begin <- 1
  yaml_end <- which(grepl("^---", rmd_lines))[2]
  yaml_content <- yaml::yaml.load(rmd_lines[yaml_begin:yaml_end])
  yaml_tbl <- tibble(
    type = "yaml",
    label = NA,
    params = list(yaml_content),
    text = NA,
    code = NA,
    heading = NA
  )

  # Get the rest of the document without yaml
  rmd_lines_no_yaml <- rmd_lines[-c(yaml_begin:yaml_end)]
  # Use hidden functions of {knitr}
  # Code extracted will be stored in a new environment
  # with `knitr:::split_file()`
  # Using `knitr::knit_code$restore()` makes sure there is no current Rmd to be
  # splitted
  # Is it compatible with the function beeing included in a Rmd file ?
  # We'll see.
  getFromNamespace("knit_log", "knitr")$restore()
  knitr::knit_code$restore()
  getFromNamespace("chunk_counter", "knitr")(reset = TRUE)
  options(knitr.duplicate.label = "allow")
  # Restore after splitting
  on.exit(options(knitr.duplicate.label = NULL))
  # restore unnamed-chunk counter
  on.exit(getFromNamespace("chunk_counter", "knitr")(reset = TRUE))
  on.exit(knitr::knit_code$restore())
  on.exit(getFromNamespace("knit_log", "knitr")$restore())


  # Split files
  out <- getFromNamespace("split_file", "knitr")(
    rmd_lines_no_yaml,
    patterns = getFromNamespace("all_patterns", "knitr")$md,
    set.preamble = TRUE
  )

  res <- tibble(
    type = sapply(out, class),
    label = sapply(out, function(x) {
      ifelse(
        !is.null(x$params$label), x$params$label, NA
      )
    }),
    params = lapply(out, function(x) {
      if (!is.null(x$params) &&
        (is.null(x$params$engine) || x$params$engine == "r")) {
        # if chunk is not 'r' chunk, it must be accounted as text
        x$params
      } else {
        NA
      }
    }),
    text = lapply(out, function(x) {
      if (inherits(x, "inline")) {
        unlist(strsplit(x$input, "\n"))
      } else if (
        !is.null(x$params) &&
          !is.null(x$params$engine) &&
          x$params$engine != "r"
      ) {
        knitr::knit_code$get(x$params$label)
      } else {
        NA
      }
    }),
    code = lapply(out, function(x) {
      if (
        !is.null(x$params) &&
          !is.null(x$params$engine) &&
          x$params$engine != "r"
      ) {
        NA
      } else if (inherits(x, "block")) {
        knitr::knit_code$get(x$params$label)
      } else {
        NA
      }
    })
  )

  # TODO - Extract headers
  # split_headers_in_text
  split_headers_from_text <- function(the_text) {
    new_group <- rep(FALSE, length(the_text))
    which_header <- grep("^#", the_text)
    if (length(which_header) != 0) {
      new_group[which_header] <- TRUE
      # Change group just after header
      which_header_plus <- 1 + which_header[
        (which_header + 1) <= length(new_group)
      ]
      if (length(which_header_plus) != 0) {
        new_group[which_header_plus] <- TRUE
      }
      groups <- cumsum(new_group)
      groups[which_header] <- paste0(groups[which_header], "-heading")

      split_text <- split(the_text, groups)
    } else {
      split_text <- list(the_text)
    }
    return(split_text)
  }

  res_split <- res
  res_split$text <- lapply(res_split$text, split_headers_from_text)
  res_split <- tidyr::unnest(res_split, cols = text)
  # Get headings
  res_split$heading <- sapply(
    seq_len(nrow(res_split)),
    function(x) {
      if (grepl("heading", names(res_split$text)[x])) {
        gsub("^#*\\s*", "", res_split$text[x])
      } else {
        NA
      }
    }
  )

  res_split$type[!is.na(res_split$heading)] <- "heading"

  # Put back yaml in 'res'
  res_full <- rbind(yaml_tbl, res_split)


  # res_full[["code"]][[2]]
  # res_full[["code"]][[4]]
  # res_full[["text"]][[4]]
  # res_full[21,]$params
  # res[20,]$text
  # as.character(res[["code"]][[20]])


  # Reste à diviser les 'inline' pour détecter les titres
  # Allez voir dans group_rmd()

  return(res_full)
}

#' Prepare all content from parsedtbl to be combined into a Rmd file
#' @param parsed_tbl A tibble with 6 columns as issued by `get_rmd_parts()`
#' @return A tibble with a new column `content` containing the content
#'  for the future rmd file
#' @noRd
get_content_parsedtbl <- function(parsed_tbl) {
  message(c(
    "TODO - This function is not yet implemented",
    "and will be added in get_rmd_parts() directly"
  ))
}

#' Combine a parsed tbl Rmarkdown file into a new Rmd file
#' @param parsed_tbl A tibble with 6 columns as issued by `get_rmd_parts()`
#' @return A Rmd file
#' @export
combine_parsed <- function(parsed_tbl) {
  # equivalent of 'parsermd::as_document()'
  # Get all code to keep, and combine into a file
  print("TODO - This function is not yet implemented")
}
