# WARNING - Generated by {fusen} from dev/flat_inflate_all_utils.Rmd: do not edit by hand

#' This function evaluates whether flat files can or can not be inflated with `inflate_all()`
#'
#' Internal function used in `inflate_all()`
#'
#' @param config_yml List. Content of the fusen config_file
#' @param pkg Character. Path of the current package
#'
#' @importFrom glue glue
#' @importFrom tibble tibble
#'
#' @return a tibble with the ability to each flat file to be inflated by inflate_all()
#' @noRd
#' @examples
#' \dontrun{
#' dummypackage <- tempfile("register")
#' dir.create(dummypackage)
#' fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))
#' dev_file <-
#'   suppressMessages(add_minimal(
#'     pkg = dummypackage,
#'     overwrite = TRUE,
#'     open = FALSE
#'   ))
#' # let's create 2 flat files
#' flat_file <- dev_file[grepl("flat_", dev_file)]
#' flat_file2 <-
#'   gsub(
#'     x = flat_file,
#'     pattern = "flat_minimal.Rmd",
#'     replacement = "flat_minimal_2.Rmd"
#'   )
#' file.copy(
#'   from = flat_file,
#'   to = flat_file2,
#'   overwrite = TRUE
#' )
#'
#' # let's inflate them to have dev/config_fusen.yml
#' suppressMessages(
#'   inflate(
#'     pkg = dummypackage,
#'     flat_file = flat_file,
#'     vignette_name = "Get started",
#'     check = FALSE,
#'     open_vignette = FALSE
#'   )
#' )
#'
#' suppressMessages(
#'   inflate(
#'     pkg = dummypackage,
#'     flat_file = flat_file2,
#'     vignette_name = "Get started2",
#'     check = FALSE,
#'     open_vignette = FALSE
#'   )
#' )
#'
#' config_yml_ref <-
#'   yaml::read_yaml(file.path(dummypackage, "dev/config_fusen.yaml"))
#'
#' # all files can be inflated with inflate_all()
#' config_yml <- config_yml_ref
#' diag <-
#'   pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)
#' print(diag)
#'
#' # let's consider the first flat file is deprecated
#' config_yml <- config_yml_ref
#' config_yml[[1]][["state"]] <- "deprecated"
#' diag <-
#'   pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)
#' print(diag)
#'
#' # let's consider the first flat file is missing from config_fusen.yaml
#' config_yml <- config_yml_ref
#' config_yml[[1]] <- NULL
#' diag <-
#'   pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)
#' print(diag)
#'
#' # let's consider that the first flat file has not inflate related params in config_fusen.yaml
#' config_yml <- config_yml_ref
#' config_yml[[1]][["inflate"]] <- NULL
#' diag <-
#'   pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)
#' print(diag)
#'
#' # let's consider a file is in config.yml but missing from dev/
#' config_yml <- config_yml_ref
#' config_yml[["missing_file.Rmd"]] <- config_yml[[1]]
#' diag <-
#'   pre_inflate_all_diagnosis(config_yml = config_yml, pkg = dummypackage)
#' print(diag)
#'
#' unlink(dummypackage, recursive = TRUE)
#' }
pre_inflate_all_diagnosis <- function(config_yml, pkg) {
  flat_files_in_dev_folder <- list.files(file.path(pkg, "dev"))
  flat_files_in_dev_folder <- flat_files_in_dev_folder[grepl(pattern = "^flat_", x = flat_files_in_dev_folder)]

  if (length(flat_files_in_dev_folder) == 0) {
    stop("There are no flat files starting with 'flat_' in the 'dev/' directory")
  }

  flat_files_status <- lapply(flat_files_in_dev_folder, function(flat) {
    if (flat %in% names(config_yml) &&
      "inflate" %in% names(config_yml[[flat]]) &&
      config_yml[[flat]][["state"]] == "active") {
      return(tibble(
        flat = flat,
        status = glue("The flat file {flat} is going to be inflated"),
        type = "message"
      ))
    } else if (flat %in% names(config_yml) &&
      config_yml[[flat]][["state"]] != "active") {
      return(tibble(
        flat = flat,
        status = glue("The flat file {flat} is not going to be inflated because it is \"inactive or deprecated\""),
        type = "message"
      ))
    } else if (!flat %in% names(config_yml)) {
      return(tibble(
        flat = flat,
        status = glue("The flat file {flat} is not going to be inflated because it is absent from the config file. Please inflate() from the flat once"),
        type = "warning"
      ))
    } else if (flat %in% names(config_yml) &&
      is.null(config_yml[[flat]][["inflate"]])) {
      return(tibble(
        flat = flat,
        status = glue("The flat file {flat} is not going to be inflated because although present in the config file, it has no inflate() parameters. Please inflate() again from the flat with this 'fusen' version"),
        type = "stop"
      ))
    }
  })

  flat_files_status <- do.call(rbind, flat_files_status)

  files_in_config_yml_but_missing_in_dev_folder <- names(config_yml)[!names(config_yml) %in% flat_files_in_dev_folder]

  if (length(files_in_config_yml_but_missing_in_dev_folder) > 0) {
    flat_files_status <- rbind(
      flat_files_status,
      tibble(
        flat = files_in_config_yml_but_missing_in_dev_folder,
        status = glue("The file {files_in_config_yml_but_missing_in_dev_folder} is not going to be inflated because it was not found, have you changed the name or did you move in another place ? Maybe you want to set the state as 'deprecated' in the config file"),
        type = "stop"
      )
    )
  }

  return(invisible(flat_files_status))
}

#' Read inflate-related parameters in config_fusen.yaml
#'
#' Internal function used in `inflate_all()`
#'
#' @param config_yml List. Content of the fusen config_file
#'
#' @return a named list with the flat files listed in config_fusen.yaml
#' and the parameters used to inflate them
#' @noRd
#' @examples
#' \dontrun{
#' config_yml <- yaml::read_yaml(system.file("inflate_all/config_fusen_with_inflate_parameters.yaml", package = "fusen"))
#' read_inflate_params(config_yml = config_yml)
#' }
read_inflate_params <- function(config_yml) {
  config_yml <- config_yml[sapply(config_yml, function(flat) flat[["state"]] == "active")]

  flat_files_names <- names(config_yml)

  flat_files_names <- flat_files_names[!flat_files_names %in% "keep"]

  if (length(flat_files_names) == 0) {
    return(NULL)
  }

  # inflate-related parameters are at level 2 of the list
  inflate_params <- lapply(flat_files_names, function(flat) {
    config_yml[[flat]][["inflate"]]
  }) %>% setNames(flat_files_names)

  inflate_params
}
