# WARNING - Generated by {fusen} from dev/flat_inflate_all.Rmd: do not edit by hand

#' Inflate all your flat files
#'
#' Inflate all the flat files stored in dev/ and starting with "flat_"
#'
#' @param pkg Path to package
#' @inheritParams inflate
#'
#' @importFrom yaml read_yaml
#' @importFrom cli cat_rule
#' @importFrom devtools check
#'
#' @return side effect. Inflates all your flat files that can be inflated.
#'
#' @export
#' @examples
#' \dontrun{
#' # Usually, in the current package run inflate_all() directly
#' # These functions changes the current user workspace
#' inflate_all()
#' # Or inflate_all_no_check() to prevent checks to run
#' inflate_all_no_check()
#' }
#'
#' # You can also inflate_all flats of another package as follows
#' # Example with a dummy package with a flat file
#' dummypackage <- tempfile("inflateall")
#' dir.create(dummypackage)
#' fill_description(pkg = dummypackage, fields = list(Title = "Dummy Package"))
#' flat_files <- add_minimal_package(
#'   pkg = dummypackage,
#'   overwrite = TRUE,
#'   open = FALSE
#' )
#' flat_file <- flat_files[grep("flat", basename(flat_files))]
#' # Inflate the flat file once
#' usethis::with_project(dummypackage, {
#'   # if you are starting from a brand new package, inflate_all() will crash
#'   # it's because of the absence of a fusen config file
#'   #
#'   # inflate_all() # will crash
#'
#'   # Add licence
#'   usethis::use_mit_license("John Doe")
#'
#'   # you need to inflate manually your flat file first
#'   inflate(
#'     pkg = dummypackage,
#'     flat_file = flat_file,
#'     vignette_name = "Get started",
#'     check = FALSE,
#'     open_vignette = FALSE,
#'     document = TRUE,
#'     overwrite = "yes"
#'   )
#'
#'   # your config file has been created
#'   config_yml_ref <-
#'     yaml::read_yaml(getOption("fusen.config_file", default = "dev/config_fusen.yaml"))
#' })
#'
#' # Next time, you can run inflate_all() directly
#' usethis::with_project(dummypackage, {
#'   # now you can run inflate_all()
#'   inflate_all(check = FALSE, document = TRUE)
#' })
#'
#' # Clean the temporary directory
#' unlink(dummypackage, recursive = TRUE)
inflate_all <- function(pkg = ".", document = TRUE, check = TRUE, open_vignette = FALSE, overwrite = TRUE, ...) {
  config_file <- getOption("fusen.config_file", default = "dev/config_fusen.yaml")

  if (!file.exists(config_file)) {
    stop("There is no fusen.config_file in your package. Your flat files must be inflated at least once manually before you can use `inflate_all()`. If you were using a fusen prior to v0.5.0.9000 you must inflate all your flat files manually once again.")
  }

  config_yml <- read_yaml(config_file)

  diag <- pre_inflate_all_diagnosis(config_yml = config_yml, pkg = pkg)
  # Run stop first only
  pre_inflate_all_diagnosis_eval(diag, type_stop = TRUE)
  # If message or warnings about flat files, show at the end of the process
  # => Is going to be
  pre_inflate_all_diagnosis_eval(diag, type_stop = FALSE)

  inflate_params <- read_inflate_params(config_yml = config_yml)

  if (length(inflate_params) == 0) {
    message("No flat files were inflated")
  } else {
    apply_inflate <- function(inflate_params, pkg, overwrite, open_vignette) {
      config_file <- getOption("fusen.config_file", default = "dev/config_fusen.yaml")
      # Change config option temporary, to be able to modify it on the fly
      config_file_tmp <- tempfile(pattern = "tempconfig")
      on.exit(file.remove(config_file_tmp))
      file.copy(config_file, to = config_file_tmp)
      options("fusen.config_file" = config_file_tmp)
      on.exit(options("fusen.config_file" = config_file))

      invisible(
        lapply(inflate_params, function(flat_file) {
          flat_file$pkg <- pkg
          flat_file$overwrite <- overwrite
          flat_file$open_vignette <- open_vignette
          flat_file$document <- FALSE
          flat_file$check <- FALSE
          suppressMessages(do.call(inflate, flat_file))
        })
      )
    }

    apply_inflate(inflate_params, pkg = pkg, overwrite = overwrite, open_vignette = open_vignette)

    # Document and check package
    document_and_check_pkg(
      pkg = pkg,
      check = check,
      document = document,
      ...
    )
  }
  invisible(pkg)
}

#' @rdname inflate_all
#' @export
inflate_all_no_check <- function(pkg = ".", document = TRUE, open_vignette = FALSE, overwrite = TRUE, ...) {
  inflate_all(pkg = pkg, document = document, check = FALSE, open_vignette = open_vignette, overwrite = overwrite, ...)
}
