# WARNING - Generated by {fusen} from dev/flat_read_inflate_params.Rmd: do not edit by hand

#' Title
#'
#' Description
#'
#' @importFrom yaml read_yaml
#'
#' @return side effect. Inflates all your flat files that can be inflated.
#'
#' @export
#' @examples
#' \dontrun{
#' inflate_all()
#' }
inflate_all <- function(pkg = ".") {
  config_file <- getOption("fusen.config_file", default = "dev/config_fusen.yaml")

  if (!file.exists(config_file)) {
    stop("There is fusen.config_file in your package. If you were using a fusen prior to v0.5.0.9000 you must inflate your flat files manually once again. Otherwise, your flat files must be inflated once before you can use inflate_all()")
  }

  config_yml <- read_yaml(config_file)

  diag <- pre_inflate_all_diagnosis(config_yml = config_yml, pkg = pkg)

  for (flat_file_diag in 1:nrow(diag)) {
    do.call(
      diag[["type"]][flat_file_diag],
      list(diag[["status"]][flat_file_diag])
    )
  }

  inflate_params <- read_inflate_params(config_yml = config_yml)

  if (length(inflate_params) == 0) {
    message("No flat files were inflated")
  } else {
    invisible(
      lapply(inflate_params, function(flat_file) {
        flat_file$pkg <- pkg
        # should we keep that?
        flat_file$overwrite <- TRUE
        suppressMessages(do.call(inflate, flat_file))
      })
    )
  }
}
