# WARNING - Generated by {fusen} from dev/flat_inflate_a_single_rmd.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @return
#' @importFrom purrr keep discard
#' 
#' @export
#' @examples
#' 
#' inflate_parameters_already_in_flat_file <- get_inflate_parameters(
#'   rmd_flat_file = system.file("files_to_parse", "flat_file_to_parse_with_extra_param.Rmd", package = "fusen"))
#' 
#' list_all_inflate_parameters(inflate_parameters_already_in_flat_file)
#' 
list_all_inflate_parameters <- function(parameters_already_in_the_flat_file){
  
  parameters_expected <- formals(fusen::inflate) %>% 
    as.list()
  
  parameters_missing <- !(names(parameters_expected) %in% parameters_already_in_the_flat_file[["parameter"]])
  
  parameters_expected_not_filled <- parameters_expected %>% 
    keep(parameters_missing) %>% 
    discard(names(.) == "...")
  
  
  parameters_already_in_the_flat_file_as_list <- as.list(parameters_already_in_the_flat_file[["value"]])
  names(parameters_already_in_the_flat_file_as_list) <- parameters_already_in_the_flat_file[["parameter"]]
  
  
  parameters_to_put_in_rmd_yml <- c(
    parameters_expected_not_filled,
    parameters_already_in_the_flat_file_as_list
  )
  
  parameters_to_put_in_rmd_yml
  
}
