# WARNING - Generated by {fusen} from dev/flat_read_inflate_params.Rmd: do not edit by hand

#' Read inflate-related parameters in config_fusen.yaml
#'
#' Internal function used in `inflate_all()`
#'
#' @return a named list with the flat files listed in config_fusen.yaml
#' and the parameters used to inflate them
#'
#' @importFrom glue glue
#' @importFrom yaml read_yaml
#'
#'
#' @examples
#' \dontrun{
#' config_fusen <- system.file("inflate_all/config_fusen_with_inflate_parameters.yaml", package = "fusen")
#' read_inflate_params(config_fusen = config_fusen)
#' }
#' @noRd
read_inflate_params <- function(config_fusen) {
  if (!file.exists(config_fusen)) {
    stop(glue("The config_fusen file does not exist"))
  }
  config_file <- read_yaml(config_fusen)
  flat_files_names <- names(config_file)
  flat_files_names <- flat_files_names[!flat_files_names %in% "keep"]

  if (length(flat_files_names) == 0) {
    return(NULL)
  }

  # inflate-related parameters are at level 2 of the list
  inflate_params <- lapply(flat_files_names, function(flat) {
    config_file[[flat]][["inflate"]]
  }) %>% setNames(flat_files_names)

  inflate_params
}
