# WARNING - Generated by {fusen} from dev/flat_sepuku-utils.Rmd: do not edit by hand

#' @importFrom yaml read_yaml
#' @noRd
#' @rdname sepuku_utils
list_flat_files_in_config_file <- function(
    config_file = getOption("fusen.config_file",
      default = "dev/config_fusen.yaml"
    )) {
  if (!file.exists(config_file)) {
    return(character(0))
  } else {
    config_yml <- yaml::read_yaml(config_file)
    return(
      unlist(
        lapply(config_yml, "[[", "path")
      )
    )
  }
}

#' @noRd
#' @rdname sepuku_utils
list_flat_files_in_dev_folder <- function(
    pkg = ".",
    folder = "dev") {
  files_identified <-
    c(
      list.files(
        path = file.path(pkg, folder),
        pattern = "flat_.*\\.Rmd",
        full.names = FALSE
      ),
      list.files(
        path = file.path(pkg, folder),
        pattern = "flat_.*\\.qmd",
        full.names = FALSE
      )
    )

  file.path(
    folder,
    files_identified
  )
}

#' List all flat files present in the package
#'
#' Search for flat files listed in fusen config file, and for rmd and qmd files starting with "flat_" in dev/ folder, and dev/flat_history folder
#'
#' @param pkg Path to package
#' @return a vector of flat files paths
#'
#' @export
#' @rdname sepuku_utils
list_flat_files <- function(pkg = ".") {
  c(
    list_flat_files_in_config_file(),
    list_flat_files_in_dev_folder(folder = "dev"),
    list_flat_files_in_dev_folder(folder = "dev/flat_history")
  ) %>%
    unique()
}
